apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
        - name: loki
          image: grafana/loki:latest
          ports:
            - containerPort: 3100
          command: ["loki","-config.file=/etc/loki/config.yaml"]
          volumeMounts:
            - name: loki-config-volume
              mountPath: /etc/loki/config.yaml
              subPath: config.yaml
      volumes:
        - name: loki-config-volume
          configMap:
            name: loki-config-map

---
apiVersion: v1
kind: Service
metadata:
  name: loki
spec:
  type: ClusterIP
  ports:
    - port: 3100
      targetPort: 3100
  selector:
    app: loki