apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
data:
  config.yaml: |
    server:
      http_listen_port: 9080  # The port Loki listens on for HTTP requests
      grpc_listen_port: 0      # Set to 0 to disable the gRPC server

    positions:
      filename: /tmp/positions.yaml  # File to track positions for scraping

    clients:
      - url: http://loki:3100/loki/api/v1/push  # Address of the Loki service to push logs

    scrape_configs:
      - job_name: system  # Name of the scrape job
        static_configs:
          - targets:
              - localhost  # Target from which to scrape logs
            labels:
              job: varlogs
              __path__: /var/log/*log  # Path to log files to be scraped