---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      containers:
        - name: tempo
          image: grafana/tempo:2.4.2
          command: ["/tempo", "--config.file=/etc/tempo/tempo.yml"]  # Make sure to use the correct executable
          ports:
            - containerPort: 3100
            - containerPort: 4318
          volumeMounts:
            - name: tempo-config
              mountPath: /etc/tempo/tempo.yml   # Mounting the directory
              subPath: tempo.yml       # Correctly specifying the file within the directory
      volumes:
        - name: tempo-config
          configMap:
            name: tempo-config    # Reference the ConfigMap

---

apiVersion: v1
kind: Service
metadata:
  name: tempo
spec:
  selector:
    app: tempo
  ports:
    - name: http
      port: 3100
      targetPort: 3100
    - name: grpc
      port: 4318
      targetPort: 4318
  type: ClusterIP