apiVersion: apps/v1
kind: Deployment
metadata:
  name: configserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configserver
  template:
    metadata:
      labels:
        app: configserver
    spec:
      containers:
        - name: configserver
          image: danielfscastro/configserver:k1
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_APPLICATION_NAME
              valueFrom:
                configMapKeyRef:
                  name: fakepay-configmap
                  key: CONFIGSERVER_APPLICATION_NAME
            - name: OTEL_SERVICE_NAME
              valueFrom:
                configMapKeyRef:
                  name: fakepay-configmap
                  key: CONFIGSERVER_APPLICATION_NAME
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: fakepay-configmap
                  key: SPRING_PROFILES_ACTIVE
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10

---

apiVersion: v1
kind: Service
metadata:
  name: configserver
spec:
  selector:
    app: configserver
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
