apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: docker.io/bitnami/kafka:3.7  # Kafka Docker image
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9092  # Port exposed for client connections
            - containerPort: 9093  # Port exposed for client connections
          env:
            - name: KAFKA_CFG_NODE_ID
              value: "0"
            - name: KAFKA_CFG_PROCESS_ROLES
              value: "controller,broker"
            - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
              value: "0@kafka.default.svc.cluster.local:9093"
            - name: KAFKA_CFG_LISTENERS
              value: "PLAINTEXT://:9092,CONTROLLER://:9093"
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka.default.svc.cluster.local:9092"
            - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
              value: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
            - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"
            - name: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
              value: "PLAINTEXT"
            - name: KAFKA_CFG_CONNECTIONS_MAX_IDLE_MS
              value: "120000"  # Increase the idle timeout
            - name: KAFKA_CFG_REQUEST_TIMEOUT_MS
              value: "60000"  # Increase request timeout to 30 seconds
          volumeMounts:
            - name: kafka-storage
              mountPath: /bitnami  # Path inside the container
          resources:
            requests:
              memory: "2Gi"
              cpu: "1"
            limits:
              memory: "4Gi"
              cpu: "2"
      volumes:
        - name: kafka-storage
          persistentVolumeClaim:
            claimName: kafka-data-pvc

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Adjust the size as needed
---

apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  type: ClusterIP  # Change to NodePort or LoadBalancer if external access is needed
  ports:
    - port: 9092
      targetPort: 9092
      protocol: TCP
      name: kafka
    - port: 9093
      targetPort: 9093
      protocol: TCP
      name: controller
  selector:
    app: kafka

---